import { Request, Response } from 'express';
import { createClient } from '@supabase/supabase-js';
import nodemailer from 'nodemailer';
import dotenv from 'dotenv';
import { isFcmReady, sendMulticastNotification, tierMatchesSubscription } from '../services/fcmPush.service';

dotenv.config();

// We absolutely MUST use the strictly protected Service Role Key, otherwise the 
// Supabase server will illegally log out the requesting Admin session mid-flight.
const supabaseAdmin = createClient(
  process.env.SUPABASE_URL || '',
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY || ''
);

export const createUser = async (req: Request, res: Response) => {
  try {
    const { email, full_name, phone, subscription_tier, password } = req.body;

    if (!email || !full_name) {
      return res.status(400).json({ error: 'System Exception: Email and Full Name are mathematically mandatory.' });
    }

    // 1. Generate Secure Alphanumeric Internal Password OR use explicit Admin definition
    const finalPassword = password || (Math.random().toString(36).slice(-8) + 'Xk9#');

    // 2. Provision Auth Identity utilizing Admin Core Logic
    const { data: authData, error: authError } = await supabaseAdmin.auth.admin.createUser({
      email,
      password: finalPassword,
      email_confirm: true, // Auto-verify the target node
      user_metadata: { full_name }
    });

    if (authError || !authData.user) {
      console.error("Supabase Admin Auth Failure: ", authError);
      return res.status(500).json({ error: 'Auth Engine Blocked User Generation.', details: authError });
    }

    // 3. The `profiles` table row is automatically generated by our PostgreSQL triggers.
    // However, we need to specifically mutate their subscription tier hierarchy since it defaults to 'free'.
    if (subscription_tier && subscription_tier !== 'free') {
      const { error: updateError } = await supabaseAdmin
        .from('profiles')
        .update({ subscription_tier })
        .eq('id', authData.user.id);

      if (updateError) {
        console.error("Profile Hierarchy Failure: ", updateError);
        // Continue anyway; the account is active.
      }
    }

    // 4. Nodemailer Dispatch Protocol
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: process.env.SMTP_PORT === '465', 
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS, // Standard Application Specific Password
      },
    });

    // Highly constructed Architectural HTML Payload
    const htmlPayload = `
      <div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; max-w-4xl; margin: 0 auto; padding: 40px; background-color: #f8fafc; color: #0f172a; border-radius: 20px;">
        <div style="text-align: center; margin-bottom: 30px;">
          <img src="https://i.ibb.co/6RJqF69/logo.png" alt="Daily-KHATA Node Ecosystem" style="width: 120px; border-radius: 10px; drop-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);" />
          <h1 style="color: #1e293b; font-size: 28px; font-weight: 900; letter-spacing: -0.5px; margin-top: 20px;">Welcome to the Ecosystem</h1>
        </div>
        
        <div style="background-color: white; padding: 40px; border-radius: 24px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05); border: 1px solid #e2e8f0;">
          <h2 style="font-weight: 800; font-size: 22px;">Hello ${full_name},</h2>
          <p style="font-size: 16px; line-height: 1.6; color: #475569;">
            Your dedicated financial tracking node has been actively provisioned on our global edge network by an Administrator. 
            You now possess the absolute pinnacle of analytical expense architecture directly at your fingertips.
          </p>
          
          <div style="margin: 35px 0; padding: 25px; background: linear-gradient(to right, #eff6ff, #f0fdf4); border: 1px solid #bfdbfe; border-radius: 16px;">
             <h3 style="margin-top: 0; color: #1e40af; font-size: 14px; text-transform: uppercase; letter-spacing: 1.5px; font-weight: 900;">Secure Auth Credentials</h3>
             <p style="margin: 10px 0; font-size: 16px;"><strong>Identifier:</strong> <span style="font-family: monospace; color: #334155;">${email}</span></p>
             <p style="margin: 10px 0; font-size: 16px;"><strong>Core Key (Password):</strong> <span style="font-family: monospace; font-size: 18px; font-weight: 900; color: #0f172a;">${finalPassword}</span></p>
          </div>
          
          <p style="font-size: 16px; line-height: 1.6; color: #475569; margin-bottom: 30px;">
            Please log in immediately via the mobile or web interface and navigate to the security sector to alter your credentials.
          </p>
          
          <a href="https://app.daily-khata.com" style="display: inline-block; background-color: #0f172a; color: white; border-radius: 12px; font-weight: 800; text-decoration: none; text-align: center; padding: 16px 32px; font-size: 16px;">Initialize Dashboard</a>
        </div>
        
        <div style="text-align: center; margin-top: 30px; color: #94a3b8; font-size: 13px;">
          <p>This is an automated architectural transmission. Do not reply to this port.</p>
          <p>&copy; 2026 Daily-KHATA Security. All privileges legally reserved.</p>
        </div>
      </div>
    `;

    // Only dispatch if SMTP is actually configured, otherwise simulate
    if (process.env.SMTP_USER && process.env.SMTP_PASS) {
       await transporter.sendMail({
         from: '"Daily-KHATA Admin Logistics" <noreply@daily-khata.com>',
         to: email,
         subject: 'Initialization: Your Secure Network Node Instructions',
         html: htmlPayload
       });
    } else {
       console.warn("SMTP_USER or SMTP_PASS mapping is missing in environment. Email simulated, transmission blocked.");
    }

    return res.status(201).json({
      message: 'Network Node provisioned & secure transmission executed successfully.',
      user_id: authData.user.id
    });

  } catch (error) {
    console.error('Terminal Server Error generating User Node:', error);
    return res.status(500).json({ error: 'Terminal backend exception.' });
  }
};

/**
 * Super-Admin Node Bypass: Deep Matrix Queries
 * Fetches all users from public.profiles disregarding Row Level Security
 */
export const getAdminCoreData = async (req: Request, res: Response): Promise<any> => {
   try {
     // Fetch minimalist raw stats directly to avoid bloating the pipe, ignoring deep select arrays
     const { data: matrixCount, error: uErr } = await supabaseAdmin.from('profiles').select('subscription_tier');
     const { data: categories, error: cErr } = await supabaseAdmin.from('categories').select('*').is('user_id', null);

     if (uErr) throw uErr;

     return res.status(200).json({ 
        stats: {
          totalUsers: matrixCount?.length || 0,
          activeSubscriptions: matrixCount?.filter(u => u.subscription_tier && u.subscription_tier !== 'free').length || 0
        },
        categories: categories || [] 
     });
   } catch (error: any) {
     return res.status(500).json({ error: error.message });
   }
};

/**
 * Highly Scalable Multi-dimensional Paginated Fetch: Users Array
 */
export const getPaginatedUsers = async (req: Request, res: Response): Promise<any> => {
   try {
     const page = parseInt(req.query.page as string) || 1;
     const limit = parseInt(req.query.limit as string) || 10;
     const offset = (page - 1) * limit;

     const { data, error, count } = await supabaseAdmin
       .from('profiles')
       .select('*', { count: 'exact' })
       .order('created_at', { ascending: false })
       .range(offset, offset + limit - 1);

     if (error) throw error;
     return res.status(200).json({
       users: data || [],
       total: count || 0,
       totalPages: Math.ceil((count || 0) / limit),
       currentPage: page
     });
   } catch(err: any) {
     return res.status(500).json({ error: err.message });
   }
};

/**
 * Super-Admin Notification Auditing: Paginated Extraction Log
 */
export const getPaginatedNotifications = async (req: Request, res: Response): Promise<any> => {
   try {
     const page = parseInt(req.query.page as string) || 1;
     const limit = parseInt(req.query.limit as string) || 10;
     const offset = (page - 1) * limit;

     const { data, error, count } = await supabaseAdmin
       .from('notifications')
       .select('*', { count: 'exact' })
       .order('created_at', { ascending: false })
       .range(offset, offset + limit - 1);

     if (error) throw error;
     return res.status(200).json({
       notifications: data || [],
       total: count || 0,
       totalPages: Math.ceil((count || 0) / limit),
       currentPage: page
     });
   } catch(err: any) {
     return res.status(500).json({ error: err.message });
   }
};

/**
 * Insert admin notification row and send FCM to matching users (by subscription tier).
 */
export const broadcastNotification = async (req: Request, res: Response): Promise<any> => {
  try {
    const { title, message, target_tier, image_url } = req.body;
    if (!title || !message || !target_tier) {
      return res.status(400).json({ error: 'title, message, and target_tier are required' });
    }

    const { data: row, error } = await supabaseAdmin
      .from('notifications')
      .insert({
        title: String(title).trim(),
        message: String(message).trim(),
        target_tier: String(target_tier).trim(),
        image_url: image_url ? String(image_url).trim() : null,
      })
      .select()
      .single();

    if (error) throw error;

    const { data: profiles, error: pErr } = await supabaseAdmin
      .from('profiles')
      .select('fcm_token, subscription_tier')
      .not('fcm_token', 'is', null);

    if (pErr) throw pErr;

    const tokens = (profiles || [])
      .filter((p: { subscription_tier?: string | null }) =>
        tierMatchesSubscription(p.subscription_tier ?? null, String(target_tier).trim())
      )
      .map((p: { fcm_token: string }) => p.fcm_token);

    let push = { successCount: 0, failureCount: 0 };
    const fcmOk = isFcmReady();

    if (fcmOk && tokens.length > 0) {
      const img = row.image_url as string | null;
      const imageUrl =
        img && (img.startsWith('http://') || img.startsWith('https://')) ? img : undefined;

      push = await sendMulticastNotification({
        tokens,
        title: row.title as string,
        body: row.message as string,
        imageUrl,
        data: {
          type: 'admin_broadcast',
          notification_id: row.id as string,
        },
      });
    }

    return res.status(201).json({
      notification: row,
      target_tier,
      eligible_devices: tokens.length,
      fcm_configured: fcmOk,
      push,
      hint: !fcmOk
        ? 'Set FIREBASE_SERVICE_ACCOUNT_JSON on the server (Firebase → Project settings → Service accounts → Generate key; paste JSON in env).'
        : tokens.length === 0
          ? 'No FCM tokens for this segment — users must open the app after login so devices register a token.'
          : undefined,
    });
  } catch (e: any) {
    console.error('broadcastNotification:', e);
    return res.status(500).json({ error: e.message || 'Broadcast failed' });
  }
};

/**
 * Super-Admin Ledger Inspection
 * Retrieve any specific node's transactions ignoring RLS
 */
export const getAdminUserLedger = async (req: Request, res: Response): Promise<any> => {
   try {
     const targetUserId = req.params.targetUserId;
     const { data, error } = await supabaseAdmin
       .from('transactions')
       .select('*, categories(name)')
       .eq('user_id', targetUserId)
       .order('transaction_date', { ascending: false });

     if (error) throw error;
     return res.status(200).json({ ledger: data || [] });
   } catch (error: any) {
     return res.status(500).json({ error: error.message });
   }
};

/**
 * Super-Admin Aggregation Engine: Global Economy Leaders
 * Identifies the top 5 network nodes by purely highest income & highest expenditure.
 */
export const getSystemPulseLeaders = async (req: Request, res: Response): Promise<any> => {
   try {
      // Pulling active financial logs. (In massive production, replace this with a discrete PostgreSQL View)
      const { data: logs, error } = await supabaseAdmin
        .from('transactions')
        .select('amount, type, user_id, profiles(full_name)');

      if (error || !logs) {
         return res.status(500).json({ error: 'Failed to access structural logs.' });
      }

      const usersIndex: Record<string, { name: string, expense: number, income: number }> = {};

      logs.forEach((trx: any) => {
         const uid = trx.user_id;
         if (!usersIndex[uid]) {
            usersIndex[uid] = { name: trx.profiles?.full_name || 'Anonymous Node', expense: 0, income: 0 };
         }
         const val = Number(trx.amount);
         if (trx.type === 'expense') usersIndex[uid].expense += val;
         else if (trx.type === 'income') usersIndex[uid].income += val;
      });

      const leaderArray = Object.values(usersIndex);
      
      const topSpenders = [...leaderArray]
         .sort((a, b) => b.expense - a.expense)
         .slice(0, 5)
         .filter(x => x.expense > 0);
         
      const topEarners = [...leaderArray]
         .sort((a, b) => b.income - a.income)
         .slice(0, 5)
         .filter(x => x.income > 0);

      return res.status(200).json({ topSpenders, topEarners });

   } catch (error) {
     return res.status(500).json({ error: 'System Pulse Aggregation failure.' });
   }
};

export const listPromoCodes = async (req: Request, res: Response): Promise<any> => {
  try {
    const { data, error } = await supabaseAdmin
      .from('promo_codes')
      .select('*')
      .order('created_at', { ascending: false });
    if (error) throw error;
    return res.status(200).json({ promos: data || [] });
  } catch (e: any) {
    return res.status(500).json({ error: e.message || 'Failed to list promo codes' });
  }
};

export const createPromoCode = async (req: Request, res: Response): Promise<any> => {
  try {
    const { code, percent_off, max_uses, expires_at } = req.body;
    if (!code || percent_off == null) {
      return res.status(400).json({ error: 'code and percent_off are required' });
    }
    const pct = Number(percent_off);
    if (Number.isNaN(pct) || pct < 1 || pct > 100) {
      return res.status(400).json({ error: 'percent_off must be between 1 and 100' });
    }
    const row = {
      code: String(code).trim().toUpperCase(),
      percent_off: pct,
      max_uses: max_uses === null || max_uses === '' || max_uses === undefined ? null : Number(max_uses),
      expires_at: expires_at ? new Date(expires_at).toISOString() : null,
      is_active: true,
    };
    const { data, error } = await supabaseAdmin.from('promo_codes').insert(row).select().single();
    if (error) throw error;
    return res.status(201).json({ promo: data });
  } catch (e: any) {
    return res.status(500).json({ error: e.message || 'Failed to create promo code' });
  }
};

export const updatePromoCode = async (req: Request, res: Response): Promise<any> => {
  try {
    const { id } = req.params;
    const { is_active, max_uses, expires_at } = req.body;
    const patch: Record<string, unknown> = {};
    if (typeof is_active === 'boolean') patch.is_active = is_active;
    if (max_uses !== undefined) patch.max_uses = max_uses === null ? null : Number(max_uses);
    if (expires_at !== undefined) patch.expires_at = expires_at ? new Date(expires_at).toISOString() : null;
    const { data, error } = await supabaseAdmin.from('promo_codes').update(patch).eq('id', id).select().single();
    if (error) throw error;
    return res.status(200).json({ promo: data });
  } catch (e: any) {
    return res.status(500).json({ error: e.message || 'Failed to update promo code' });
  }
};
